version: '3'

services:
  localhost:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=postgres

  app:
    build: ./
    container_name: java-ap
    ports:
      - '8080:8080'